version: '3.8'

name: marklogic_new_tool

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # Simplifies restoring the dvdrental.tar into Postgres.
      - ./docker/postgres:/opt
    ports:
      - "5432:5432"

  # Postgres DVD rental example - https://www.postgresqltutorial.com/postgresql-getting-started/postgresql-sample-database/
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    depends_on:
      - postgres

  marklogic:
    image: "marklogicdb/marklogic-db:11.1.0-centos-1.1.0"
    platform: linux/amd64
    environment:
      - MARKLOGIC_INIT=true
      - MARKLOGIC_ADMIN_USERNAME=admin
      - MARKLOGIC_ADMIN_PASSWORD=admin
    volumes:
      - ./docker/marklogic/logs:/var/opt/MarkLogic/Logs
    ports:
      - 8000-8003:8000-8003
